// Generated by https://quicktype.io

export interface Plan {
	data: Data
	included: any[]
	meta: Meta
}

export interface Data {
	type: string
	id: string
	attributes: Attributes
	relationships: Relationships
	links: Links
}

export interface Attributes {
	can_view_order: boolean
	created_at: Date
	dates: string
	files_expire_at: Date
	items_count: number
	last_time_at: Date
	multi_day: boolean
	needed_positions_count: number
	other_time_count: number
	permissions: string
	plan_notes_count: number
	plan_people_count: number
	planning_center_url: string
	prefers_order_view: boolean
	public: boolean
	rehearsable: boolean
	rehearsal_time_count: number
	reminders_disabled: boolean
	series_title: string
	service_time_count: number
	short_dates: string
	sort_date: Date
	title: string
	total_length: number
	updated_at: Date
}

export interface Links {
	all_attachments: string
	attachments: string
	attendances: string
	contributors: string
	import_template: string
	item_reorder: string
	items: string
	live: string
	my_schedules: string
	needed_positions: string
	next_plan: string
	notes: string
	plan_times: string
	previous_plan: string
	series: null
	signup_teams: string
	team_members: string
	self: string
	html: string
}

export interface Relationships {
	service_type: CreatedBy
	next_plan: CreatedBy
	previous_plan: CreatedBy
	attachment_types: AttachmentTypes
	series: LinkedPublishingEpisode
	created_by: CreatedBy
	updated_by: CreatedBy
	linked_publishing_episode: LinkedPublishingEpisode
}

export interface AttachmentTypes {
	data: any[]
}

export interface CreatedBy {
	data: Parent
}

export interface Parent {
	type: string
	id: string
}

export interface LinkedPublishingEpisode {
	data: null
}

export interface Meta {
	can_include: string[]
	parent: Parent
}
