// Generated by https://quicktype.io

export interface Schedule {
	links: Links
	data: Datum[]
	included: any[]
	meta: Meta
}

export interface Datum {
	type: string
	id: string
	attributes: Attributes
	relationships: Relationships
	links: Links
}

export interface Attributes {
	can_accept_partial: boolean
	can_accept_partial_one_time: boolean
	can_rehearse: boolean
	dates: string
	decline_reason: null
	organization_name: string
	organization_time_zone: string
	organization_twenty_four_hour_time: boolean
	person_name: string
	plan_visible: boolean
	plan_visible_to_me: boolean
	position_display_times: null
	responds_to_name: string
	service_type_name: string
	short_dates: string
	sort_date: Date
	status: string
	team_name: string
	team_position_name: string
}

export interface Links {
	self: string
}

export interface Relationships {
	person: Organization
	service_type: Organization
	organization: Organization
	plan_person: Organization
	plan: Organization
	team: Organization
	responds_to_person: Organization
	times: Times
}

export interface Organization {
	data: Parent
}

export interface Parent {
	type: string
	id: string
}

export interface Times {
	data: Parent[]
}

export interface Meta {
	onboarding: boolean
	total_count: number
	count: number
	can_order_by: string[]
	can_query_by: string[]
	can_include: string[]
	can_filter: string[]
	parent: Parent
}
